### ISSUE TITLE
switching off the display makes OSMTracker forget tiles

### ISSUE THREAD

**Issue by PontiacCZ** [nguillaumin/osmtracker-android#61] opened 2016-02-07 17:13 UTC
**Screen 1**: OSMTracker is tracking, all tiles in the current area are downloaded. Then I switch off the display to save battery...
![pic1](https://cloud.githubusercontent.com/assets/9153595/12873685/529037b2-cdc4-11e5-851f-b70679e44270.png)

**Screen 2**: after switching on the display I see this - couple of tiles are missing. OSMTracker reloads them, it takes some time and data from my data limit. In the end everything is loaded just like in the first screenshot. Then again I turn off the display...
![pic2](https://cloud.githubusercontent.com/assets/9153595/12873686/529b3f22-cdc4-11e5-9813-6a65636ce799.png)

**Screen 3**: ... to find out that after switching it on I have lost another tiles. And again, it starts reloading the missing tiles.
![pic3](https://cloud.githubusercontent.com/assets/9153595/12873687/529c38e6-cdc4-11e5-9fd8-3275766ad9e5.png)

Sometimes when mapping I get to areas without service and then no reload can occur so I am a little bit blinded.

OSMTracker for Android v0.6.11
HW: Nexus 6 (Android 6.0.1)

**Comment by nguillaumin** [comment] 2016-02-08 11:05
We use the [OSMDroid](https://github.com/osmdroid/osmdroid) library to draw the map, so it's quite certainly an issue with it, although I couldn't find a similar one in their bug tracker.

Since I lack the time to work on the app, it's unlikely to get fixed as I would need time to make a reproducible case for the OSMDroid guys...

**Comment by PontiacCZ** [comment] 2016-02-09 06:29
Just wanted to let you know that I posted this problem to OSMDroid's issue list as well (see the link above) and obtained an answer which might be of some help. Not sure.

**Comment by nguillaumin** [comment] 2016-02-09 07:48
Hehe, I was sure we would end up bouncing the issue between OSMTracker and OSMDroid :)

Since I'm not the one who implemented the map view in OSMTracker, I have no idea how it's configured at our end. I'll have a look when time permits.

**Comment by nguillaumin** [comment] 2016-02-09 07:52
Also, if you could:
* Try to export a track as GPX and confirm it works
* Go to the "About" screen, click on the debug button and paste the content here

Cheers.

**Comment by PontiacCZ** [comment] 2016-02-09 10:45
1) I use OSMTracker about once a week, no problem with exported GPXs, they load into JOSM fine. So the GPX files exported from the OSMTracker definitely work.
2) I did tap on the Debug button and I guess it was supposed to export a diag file, but this is what I got instead:
![screenshot_20160209-114145](https://cloud.githubusercontent.com/assets/9153595/12914024/62cccb72-cf22-11e5-90bc-a88fb0d7d85a.png)

**Comment by nguillaumin** [comment] 2016-02-09 11:09
Thanks, that was what I was after. That confirms that there's no problem writing to the external storage.

There are a few updates on the [upstream issue](https://github.com/osmdroid/osmdroid/issues/263) which seem to suggest it's indeed a bug with OSMDroid (they managed to reproduce it with a different application than OSMTracker). We'll see what happens...

**Comment by nguillaumin** [comment] 2016-02-23 07:53
Upstream issue is now fixed, we'll have to wait for them to package a release, and update our dependency to the new version.

**Comment by PontiacCZ** [comment] 2016-02-23 14:02
I've been watching the OSMDroid's issue as well. Looking forward to the updated version. :-)

**Comment by PontiacCZ** [comment] 2016-11-18 06:52
Have they already packaged the fixed release?

**Closed** 2016-11-20 20:09 UTC
Labels: bug, osmdroid

**Comment by nguillaumin** [comment] 2016-11-20 20:11
They have, I just upgraded it. I'll try to release soon.
